taxonomy_breadcrumb.settings:
  type: mapping
  label: Settings
  mapping:
    taxonomy_breadcrumb_page_title:
      type: boolean
    taxonomy_breadcrumb_include_nodes:
      type: integer
    taxonomy_breadcrumb_include_node_title:
      type: boolean
