<?php

/**
 * @file
 * Contains wil_url.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wil_url_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wil_url module.
    case 'help.page.wil_url':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

